version: '3.9'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: "npm start"
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USERNAME=your_postgres_username
      - PG_PASSWORD=your_postgres_password
      - PG_DATABASE=your_postgres_database
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./server:/app
    depends_on:
      - db
    # Remove the CMD instruction from here; it's already defined in the Dockerfile
  db:
    image: postgres:latest
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:${PG_PORT}"
