
version: '3.3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.local
    restart: always
    # env_file: .env
    ports:
      - "3000:3000"
    # volumes:
    #   - "./packages/client/src:/usr/src/app/src"
    depends_on:
      - server
    command: "npm start"
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=farm
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=smart_farm
    volumes:
      - ./server:/app
    # depends_on:
    #   - db
  # db:
  #   image: postgres:latest
  #   restart: always
  #   container_name: db
  #   env_file: .env
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #     # PGDATA: /var/lib/postgresql/data
  #     POSTGRES_USER: farm
  #     POSTGRES_DB: smart_farm
  #   ports:
  #     - "5433:5432"
    # volumes:
    #   - ./server/database:/var/lib/postgresql/data