version: '3'

services:
  database:
    build: 
      context: ./server/src/database
      dockerfile: Dockerfile
    # environment:
    #   POSTGRES_DB: smart_farm
    #   POSTGRES_USER: farm
    #   POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run start:dev"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.local
    ports:
      - "80:80"
