version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=farm
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=smart_farm
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=farm
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=smart_farm
